### PR TITLE
GNOME 3.32 support

### PR DESCRIPTION
**Pull request by kirbyfan64**
This does two things:

- Ports over to ES6 classes to allow to work under GNOME 3.32. Basically, this drops `Lang.Class` and `Lang.bind`. This also means that everything under 3.32 has to be dropped, unless you want to add in a ton of LOC for some awkward shim code...
- Uses the Adwaita 3.30 emoji icons instead of the current mix of random system + some custom symbolic icons. I had noticed the two custom ones weren't working, then after I bit of research I found out the [behavior of appended a directory with simply with icon files inside is considered a legacy feature](https://developer.gnome.org/gtk3/stable/GtkIconTheme.html#gtk-icon-theme-set-search-path). Given that this is now 3.32+ anyway, I figured it would be best to use these.

I understand if this can't be merged quite yet, due to your distro still being on 3.30, but I figured I'd open this here anyway for early feedback, as well as to allow others with 3.32 to see this PR and be able to try it out.

(Unfortunately, some whitespace stripping got mixed with this. You can add `?w=1` to the diff page to view this without those changes.)

### CODE REVIEW

**Comment by maoschanz** [comment]
Concerning 3.32 i trust that it's working, but I'm expecting that a majority of users are on Ubuntu LTS so I'm not sure about the Adwaita 3.30 icons. I'll test it in an Ubuntu VM tomorrow.

**Comment by maoschanz** [comment]
I see you updated the manifest quite restrictively, ES6 classes are not very new https://2017.guadec.org/wp-content/uploads/2017/06/Philip-Chimento-GUADEC-2017-Modern-Javascript-in-GNOME.pdf i want to support as many versions as possible, so from 3.26 to 3.32

**Comment by kirbyfan64** [comment]
> I see you updated the manifest quite restrictively, ES6 classes are not very new 

Shell didn't use them until 3.32, however, so ES6 syntax cannot be used to derive from Shell and GTK+ classes on 3.30 and older. OTOH with 3.32, only ES6 syntax is supported. FWIW there have been other extensions that had to do the same thing.

(On the bonus side, this breakage made icon grids draw faster, so this extension loads the emoji grids more quickly.)

**Comment by maoschanz** [comment]
Damn, i really should have prefer composition over inheritance. I'll re-refactor later i guess

**Comment by kirbyfan64** [comment]
❤

**Pull request merged**
